name: ml
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - jupyterlab
  - pip
  - ipywidgets
  - plotly
  - pip:
      - matplotlib
      - pandas
      - scikit-learn
      - anywidget
      - statsmodels
      - seaborn